# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 647c1fd99a826ff7eb355e0fc0c7ccaab865e0d7e9e37197b3d0e53fc09a3426fdcdcecd990be025353ae8c711ebd3d3f560461ea9a211bfbda9db2b3c35fb63

test:
  secret_key_base: 90d488568b76a66871ff3b5318e98b253e9be3eb8f491920cb4fdd39bf93a22e933383bfbbc87a44e030dbb1a2902b3253785ae5ed92a2a3dafa7e7e763a7a53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
